### PR TITLE
Upgrade to Ember CLI 2.13, Babel 6, ESLint

### PR DESCRIPTION
**Pull request by raido**
This should be merged after - https://github.com/josemarluedke/ember-cli-segment/pull/34 and tagging v1.0 officially.

All 6 ember try scenarios are green.

### CODE REVIEW

**Comment by josemarluedke** [comment]
Could you rebase with master?

**Comment by raido** [comment]
All green (y)

**Comment by josemarluedke** [comment]
@raido Thank you so much for working on this! I really appreciate it.

**Comment by josemarluedke** [comment]
Published as v2.0.0. Thanks again for working on this.

**Pull request merged**
