### PR TITLE
Ember 1.13.x and 2.x compatibility and test

### PR DESCRIPTION
**Pull request by kmiyashiro**
* [x] Upgrade ember-cli to 1.13.14
* [x] Upgrade ember to 1.13
* [x] Add ember-try to test ~~1.10, 1.11~~, 1.13, release, beta, canary
* ~~Make tests pass in 1.11+~~
* [x] Make compatible for ember 1.13+
* [x] Make compatible for ember 2.x
* [x] Add ember-test configuration to travis

Update for 1.13.x and 2.x, not backwards compatible.

### CODE REVIEW

**Comment by kmiyashiro** [comment]
I can't seem to get <1.13 working with instance initializers in acceptance tests. I'm tempted to just skip 1.11-1.12 and go for 1.13-2.x compat.

**Comment by asteinlein** [comment]
+1 for 1.13-2.x support only, @kmiyashiro – no need to support ancient versions IMHO when people on older relases can simply use an older version of this library. Big thanks for working on this, I hope a release can be relatively imminent. :)

**Comment by josemarluedke** [comment]
Awesome work! +1 for 1.13.+ support only.

Can you get the tests passing?

I will look more close to it latter today.

**Comment by kmiyashiro** [comment]
ok, 1.13+ it is. Tests are already passing for 1.13, but with deprecations. I will clean those up and then maybe just get 2.x compatibility in another PR.

**Comment by kmiyashiro** [comment]
Yay, all green.

I used https://github.com/rwjblue/ember-getowner-polyfill as the recommended backwards compatible way to get around the container/instance/lookup deprecations, but it's still triggering deprecation messages in 2.3. This is a bug, confirmed with @rwjblue

**Comment by josemarluedke** [comment]
Just pushed v0.1.0 to NPM! Thank you so much for your work in here.

**Comment by kmiyashiro** [comment]
:+1:

**Pull request merged**
